# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\mys\PycharmProjects\AdanceToo\topwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopWindow(object):
    def setupUi(self, TopWindow):
        TopWindow.setObjectName("TopWindow")
        TopWindow.resize(983, 622)
        self.centralwidget = QtWidgets.QWidget(TopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(135, 0))
        self.widget.setMaximumSize(QtCore.QSize(135, 16777215))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("background-color: rgb(64, 171, 255);")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(-10, 130, 151, 101))
        self.pushButton.setStyleSheet("font: 20pt \"华光大黑_CNKI\";\n"
"background-color: rgb(64, 171, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(-10, 230, 151, 101))
        self.pushButton_2.setStyleSheet("font: 20pt \"华光大黑_CNKI\";\n"
"background-color: rgb(64, 171, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(-10, 330, 151, 101))
        self.pushButton_3.setStyleSheet("font: 20pt \"华光大黑_CNKI\";\n"
"background-color: rgb(64, 171, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 141, 130))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 1, 1, 1)
        TopWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TopWindow)
        self.statusbar.setObjectName("statusbar")
        TopWindow.setStatusBar(self.statusbar)
        self.actionCOM = QtWidgets.QAction(TopWindow)
        self.actionCOM.setObjectName("actionCOM")
        self.actionTCP_UDP = QtWidgets.QAction(TopWindow)
        self.actionTCP_UDP.setObjectName("actionTCP_UDP")
        self.actionUSB = QtWidgets.QAction(TopWindow)
        self.actionUSB.setObjectName("actionUSB")

        self.retranslateUi(TopWindow)
        QtCore.QMetaObject.connectSlotsByName(TopWindow)

    def retranslateUi(self, TopWindow):
        _translate = QtCore.QCoreApplication.translate
        TopWindow.setWindowTitle(_translate("TopWindow", "MainWindow"))
        self.pushButton.setText(_translate("TopWindow", "串口"))
        self.pushButton_2.setText(_translate("TopWindow", "TCPUDP"))
        self.pushButton_3.setText(_translate("TopWindow", "USB"))
        self.actionCOM.setText(_translate("TopWindow", "COM"))
        self.actionTCP_UDP.setText(_translate("TopWindow", "TCP&UDP"))
        self.actionUSB.setText(_translate("TopWindow", "USB"))
