# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TopWindow(object):
    def setupUi(self, TopWindow):
        TopWindow.setObjectName("TopWindow")
        TopWindow.resize(983, 622)
        self.centralwidget = QtWidgets.QWidget(TopWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(100, 0))
        self.widget.setMaximumSize(QtCore.QSize(100, 16777215))
        self.widget.setBaseSize(QtCore.QSize(0, 0))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0227273 rgba(255, 255, 255, 255), stop:1 rgba(59, 59, 59, 162));")
        self.widget.setObjectName("widget")
        self.SerialpushButton = QtWidgets.QPushButton(self.widget)
        self.SerialpushButton.setGeometry(QtCore.QRect(-10, 130, 121, 101))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SerialpushButton.setFont(font)
        self.SerialpushButton.setStyleSheet("font: 22pt \"华文中宋\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.SerialpushButton.setFlat(False)
        self.SerialpushButton.setObjectName("SerialpushButton")
        self.TCPpushButton = QtWidgets.QPushButton(self.widget)
        self.TCPpushButton.setGeometry(QtCore.QRect(-10, 230, 121, 101))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TCPpushButton.setFont(font)
        self.TCPpushButton.setStyleSheet("font: 22pt \"华文中宋\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.TCPpushButton.setFlat(False)
        self.TCPpushButton.setObjectName("TCPpushButton")
        self.USBpushButton = QtWidgets.QPushButton(self.widget)
        self.USBpushButton.setGeometry(QtCore.QRect(-10, 330, 121, 101))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.USBpushButton.setFont(font)
        self.USBpushButton.setStyleSheet("font: 22pt \"华文中宋\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(64, 65, 66);\n"
"")
        self.USBpushButton.setFlat(False)
        self.USBpushButton.setObjectName("USBpushButton")
        self.TCPpushButton.raise_()
        self.SerialpushButton.raise_()
        self.USBpushButton.raise_()
        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 1, 1, 1)
        TopWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TopWindow)
        self.statusbar.setObjectName("statusbar")
        TopWindow.setStatusBar(self.statusbar)
        self.actionCOM = QtWidgets.QAction(TopWindow)
        self.actionCOM.setObjectName("actionCOM")
        self.actionTCP_UDP = QtWidgets.QAction(TopWindow)
        self.actionTCP_UDP.setObjectName("actionTCP_UDP")
        self.actionUSB = QtWidgets.QAction(TopWindow)
        self.actionUSB.setObjectName("actionUSB")

        self.retranslateUi(TopWindow)
        QtCore.QMetaObject.connectSlotsByName(TopWindow)

    def retranslateUi(self, TopWindow):
        _translate = QtCore.QCoreApplication.translate
        TopWindow.setWindowTitle(_translate("TopWindow", "EasyTool"))
        self.SerialpushButton.setText(_translate("TopWindow", "串口"))
        self.TCPpushButton.setText(_translate("TopWindow", "TCP"))
        self.USBpushButton.setText(_translate("TopWindow", "USB"))
        self.actionCOM.setText(_translate("TopWindow", "COM"))
        self.actionTCP_UDP.setText(_translate("TopWindow", "TCP&UDP"))
        self.actionUSB.setText(_translate("TopWindow", "USB"))
